### PR TITLE
fix: add handling for exit codes on error

### LINKED ISSUE #31: exit code is always 0
* Operating System: Ubuntu 18.04
* Node Version: v8.10.0
* NPM Version: 6.0.0
* webpack Version: 4.9.1
* webpack-command Version: 0.2.0

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior
If any errors occurs I expect some exit code > 0.

### Actual Behavior
exit code is 0

### How Do We Reproduce?

put some invalid code before running webpack

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

The author is MIA, but pretty sure this resolves #31. Exit code for webpack-command is always 0. I've added code to handle rejected compilations, display the error and exit with a nonzero. This also contains a change to the order of operations in `compiler.js` whereby reporters are given the chance to do something if there's an error in the build. 

### Breaking Changes

None

### Additional Info

_This really needs testing before it can be merged_ If anyone has suggestions for tests to force a build to fail with an error, rather than going through the build with errors, please post your suggestions. I'm at a bit of a loss.

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -111,6 +112,19 @@ ${commandHelp()}
...
+      const { error: log } = console;
+
+      if (!(error instanceof Error)) {
+        error = new Error(
+          `webpack-command failed with a value of: ${inspect(error)}`
+        );
+      }
+
+      log(error.stack);
+      process.exit(1);
```
Comment (ooflorent) [inline lib/cli.js]: `process.exitCode = 1` would be better

Comment (shellscape) [reply lib/cli.js]: why is that? do you have documentation that states one method is better versus another? we want to force a process exit here.

Comment (elliottsj) [reply lib/cli.js]: From the Node.js docs: https://nodejs.org/api/process.html#process_process_exit_code

>Calling process.exit() will force the process to exit as quickly as possible even if there are still asynchronous operations pending that have not yet completed fully, including I/O operations to process.stdout and process.stderr.

>In most situations, it is not actually necessary to call process.exit() explicitly. The Node.js process will exit on its own if there is no additional work pending in the event loop. The process.exitCode property can be set to tell the process which exit code to use when the process exits gracefully.

Comment (shellscape) [reply lib/cli.js]: aye. so with the intent here, keeping it as-is is what we want. a full-stop to operations.

Comment (ooflorent) [reply lib/cli.js]: Well, letting node flush all pending low-level IO operations is always a good idea. It's up to you to decide.

**Comment by elliottsj** [comment]
Looking forward to this getting released 👍

File: lib/cli.js (hunk 1 above)
Comment (shellscape) [reply lib/cli.js]: @ooflorent gave some thought and I agree with you. Will be pushing a change shortly.

**Comment by MrMamen** [comment]
I've tested it, at it still doesn't seem to give expected result. In webpack-cli I get an error like this:

> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Then with webpack-command I get an error like this:

> ✖ 2 problems (2 errors, 0 warnings)
> Done in 14.18s.

inspecting code like this reaveals that the exit code is 0 despite 2 problems found:

> echo $?                                                        
> 0

**Comment by ankurk91** [comment]
Same here as @MrMamen
It always return exit code `0`.
I can share reproduction if you guys want.

I want this to be fixed as our CI is deploying to server even if build fails.

**Comment by shellscape** [comment]
@ankurk91 yes a reproducible failing build for your scenario would be helpful

**Comment by ankurk91** [comment]
@shellscape 
Here is the minimal repo, you can also see build logs on travis-ci.

https://github.com/ankurk91/webpack-command-exit-code-issue

**Comment by shellscape** [comment]
@ankurk91 thank you, I will have a look at this soon.

**Comment by shellscape** [comment]
I have a fix for this. PR will be going up today.
